# Enhanced ArgoCD Configuration for EKS Microservices
# This includes additional applications and better monitoring

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-microservices
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: eks-microservices
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/ckanth15/eks-microservices.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas
  health:
    initialDelaySeconds: 30
    periodSeconds: 60
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: monitoring
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/ckanth15/eks-microservices.git
    targetRevision: HEAD
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 5
  health:
    initialDelaySeconds: 30
    periodSeconds: 60
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: jenkins
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/ckanth15/eks-microservices.git
    targetRevision: HEAD
    path: k8s/jenkins.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 5
  health:
    initialDelaySeconds: 30
    periodSeconds: 60
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: ingress
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/ckanth15/eks-microservices.git
    targetRevision: HEAD
    path: k8s/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
  health:
    initialDelaySeconds: 30
    periodSeconds: 60
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: database
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/ckanth15/eks-microservices.git
    targetRevision: HEAD
    path: k8s/database
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
  health:
    initialDelaySeconds: 30
    periodSeconds: 60
